### ISSUE TITLE
AttributeError when running test_integration

### ISSUE THREAD

**Issue by vagetablechicken** [XiaoMi/pegasus-python-client#8]
```
test_integration
  TestIntegration
    test_0_replica_scan_exception ...                                      [OK]
    test_1of3_replica_restart ...                                       [ERROR]
    test_1of5_replica_restart ...                                       [ERROR]
    test_1of5_replica_stop ...                                          [ERROR]
    test_1of5_replica_stop_and_start ...                                [ERROR]
    test_1of5_replica_stop_and_start_with_meta_stop_and_start ...       [ERROR]
    test_2of5_replica_stop ...                                          [ERROR]
    test_3of3_replica_restart ...                                       [ERROR]
    test_5of5_replica_restart ...                                       [ERROR]
    test_can_not_connect ...                                               [OK]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/hw/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/hw/.local/lib/python2.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "tests/test_integration.py", line 140, in test_1of3_replica_restart
    yield self.check_data()
  File "/home/hw/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/hw/.local/lib/python2.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "tests/test_integration.py", line 116, in check_data
    ret = yield self.loop_op()
  File "/home/hw/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "tests/test_integration.py", line 107, in loop_op
    ret = yield self.c.get(self.TEST_HKEY + str(i), self.TEST_SKEY, 200)
  File "pypegasus/pgclient.py", line 719, in get
    return session.operate(op, timeout)
  File "pypegasus/pgclient.py", line 90, in operate
    self._reqs[seqid] = dr
exceptions.AttributeError: 'ReplicaSession' object has no attribute '_reqs'

test_integration.TestIntegration.test_1of3_replica_restart
```
所有ERROR均为`exceptions.AttributeError: 'ReplicaSession' object has no attribute '_reqs'`

打印当前模块的属性列表，写法示例：
```
        logger.info('%s', dir(self))
        if not hasattr(self, '_reqs'):
            logger.error('no attr _reqs, %s', dir(self))
```
测试发现，一开始属性列表正常，在某一次get时该实例真的没有_reqs属性了，其余属性均存在。

**Comment by hycdong** [comment]
找不到_reqs的原因我找到了
是thrift 0.11.0把_reqs删掉的，下面是0.11.0的代码
https://github.com/apache/thrift/blob/0d8da22dba430c379de04ff48e507e7277f4ea21/lib/py/src/transport/TTwisted.py#L84
0.9.3没有
https://github.com/apache/thrift/blob/53dd39833a08ce33582e5ff31fa18bb4735d6731/lib/py/src/transport/TTwisted.py#L84
关于怎么去优化session那块还需要再详细看

**Comment by vagetablechicken** [comment]
`exceptions.AttributeError: 'ReplicaSession' object has no attribute '_reqs' `不是唯一可能的error。经昱晨测试，也会出现`exceptions.AttributeError: 'NoneType' object has no attribute '_reqs' `
问题在于
```
    def connectionLost(self, reason=connectionDone):
        # the called errbacks can add items to our client's _reqs,
        # so we need to use a tmp, and iterate until no more requests
        # are added during errbacks
        if self.client:
            tex = TTransport.TTransportException(
                type=TTransport.TTransportException.END_OF_FILE,
                message='Connection closed (%s)' % reason)
            while self.client._reqs:
                _, v = self.client._reqs.popitem()
                v.errback(tex)
            del self.client._reqs
            self.client = None
```
和pegasus session持有的是同一个client，在connectionLost执行时，session可能还在往_reqs里加入request（operate函数）。而恰巧，我缩减了测试用例，精简后的测试常常是在` del self.client._reqs`时operate企图将request加入_reqs。

**Comment by vagetablechicken** [comment]
thrift的TTwisted.ThriftClientProtocol这段代码经过几次变化，注释和代码已经不匹配了。注释和https://issues.apache.org/jira/browse/THRIFT-2883?attachmentOrder=asc 的patch比较匹配，errbacks可能想要在_reqs中加入新的request（主要是为了retries），就通过拷贝一个tmp，迭代tmp，避开因为向_reqs加入新的request而引发`exceptions.RuntimeError: dictionary changed size during iteration`。但是真正合入官方代码的是https://github.com/apache/thrift/pull/314。
但无论哪种写法，它们的主要思想都是要把_reqs所有request都处理了，并没有考虑在清空途中或者之后，其他地方可能使用_reqs。而python client刚好执行operate操作_reqs，所以引发了错误。

**Comment by vagetablechicken** [comment]
鉴于目前python client并没有想要利用errback做retry，现阶段的bug修复方法考虑为：
1. 重命名Session的_reqs，和thrift的使用的_reqs区分开，避免会引发这类bug
2. 限制thrift版本，不使用0.10.0及以上的版本，并且注意不可以使用errback操作_reqs
